### ISSUE TITLE
Edits and Improvements to Git Action

### ISSUE THREAD

**Issue by FalgunMalhotra** [advaithsrao/694Team14Dbms2023#9]
- [x] Change 'lint' to 'dependency' on line 8 to respective job names
- [x] Add test for lint.
- [x] Added test for safety(dependency tracker)
- [x] Parallel workflow setup.
- [ ] Test connection for relational and non-relational databases.

**Comment by advaithsrao** [comment]
**April 15 2023 Update**
CC: @FalgunMalhotra 

_Done_ 
- Change 'lint' to 'dependency' on line 8 to respective job names
- Added test for lint
- Added test for safety(dependency tracker)
- Parallel workflow setup done

_To Do_
- Test connection for relational and non-relational database
